apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app-main
  template:
    metadata:
      labels:
        app: springboot-app-main
    spec:
      containers:
        - name: my-springboot-app
          image: insurancerepo.azurecr.io/insurancerepo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-main
    k8s-app: springboot-app-main
  name: springboot-app-main
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-main
